.github/workflows/publish.yml

Our cosign version is tracking an old commit, this updates it to
track main and hopefully as a side effect will end up using endpoint
fulcio.sigstore.dev
instead of v1.fulcio.sigstore.dev
https://github.com/sigstore/fulcio/issues/753

Update cosign installer to track main

---

.github/workflows/publish.yml

Test plan:
After merging https://github.com/chantra/runner/pull/2 and having https://github.com/chantra/runner/actions/runs/3185139746 build and publish the container, https://github.com/chantra/runner/pkgs/container/runner/44341109?tag=staging shows both arm64 and amd64 as available architectures.
Then I could download the runner, run it, and attach it as a runner of https://github.com/chantra/gh_runner_tests/
Finally, I could schedule a job: https://github.com/chantra/gh_runner_tests/actions/runs/3161797207/jobs/5194792546
```
[ec2-user@ip-10-0-3-73 runner]$ sudo docker run -ti ghcr.io/chantra/runner:staging bash
root@152208d8dd90:/actions-runner# ./config.sh --url https://github.com/chantra/gh_runner_tests --token <token_here> …
```

Add support for arm64 container

---

Dockerfile

Put the repository in /etc/apt/sources.list.d/llvm.list instead of appending it to /etc/apt/sources.list.
This avoid having the repository duplicated multiple times.

Add LLVM repo in a separate file

---

.github/workflows/publish.yml
s390x.Dockerfile

This change allows building and publishing s390x runners directly from this repo.
This has the advantage that:
- all the architectures that are running our runners will be able to pull the runner in a consistent manner.
- s390x runners, will not need to build the runners locally anymore.
- The CI will take care of updating the runner daily.
- Updating the version of the runner will be a matter of updating the version in s390x.Dockerfile
The only con so far is that there may be a window of time when the s390x build is not available right after the x86_64/arm64's new containers are available. Essentially a matter of 10 min or so.
During that time, the runners will still ave an old version of the runners available locally. It is realistically only a problem when a new host is provisioned, …

Build s390x runners

---

.github/workflows/publish.yml
s390x.Dockerfile

This change will build the s390x containers alongside the arm64 and amd64 ones.
Becuase s390x dockerfile is different than the ones for arm64/amd64, we can't generate a multi-arch container with the same tag (say `main`) in 1 step. Having the 2 steps causes the latest step to nuke the tag for the archs from the first step, making  the container unavailable for that arch, which is how we ended up reverting the first attempt to build s390x containers: 4f09482052c1df07aa46586098ce83ace1c8bfe6
For this reason, we are now creating a tag for every single arch in the form `{arch}-{tag}`, e.g `s390x-main`. This also allows us to build the 3 archs in parallel as they are all independent steps.
A separate libbpf/ci diff will be needed to get runners to pick up the new tag.

build s390x containers

---

s390x.Dockerfile

Volumes get created and deleted each time the container restart. the non-s390x containers do not have this volume, so let's uniformize this bit too.
We could benefit from volumes to keep the logs generated by the actions-runner, but this would be done by using a consitent volume across restarts (as opposed to new anonymous volume on each restarts).

s390x: remove the volume

---

.github/workflows/version_bump.yml

Get the last release from GH API and update the relevant line in the Dockerfile

[workflow] Add workflow to automatically bump the s390x runner version

---

Dockerfile

It seems that GH is sometime generating new release event for older releases: https://github.com/orgs/community/discussions/12225
this causes older releases to be marked as latest and break our runners:
https://github.com/myoung34/docker-github-actions-runner/issues/277

Force v2.301.1 to work around myoung34/docker-github-actions-runner#277

---

.github/workflows/publish.yml

Our runs started to fail with https://gist.github.com/chantra/6ba6cdc65bd462bf082e8d8d0d91d02a
This is similar to https://github.com/sigstore/cosign-installer/pull/110

Add `--yes` to `cosign sign` command line.

---

Dockerfile
s390x.Dockerfile

We will end up installing those later, but can save a bit of time by installing them when the containers are built.
At run time, we will detect if they need to be updated and install them then.

pkg: add a few packages that we will depend on during testing

---

.github/workflows/publish.yml
Dockerfile
s390x.Dockerfile

This PR adds support for Ubuntu 24.04 GH runner containers.
First, `Dockerfile` are modified to take an option `--build-arg` to set the Ubuntu version to build. We default to `focal`.
Second, the GH action is modified to build both Ubuntu versions. This also requires to change the tag format from `{branch}-{arch}` to `{branch}-{ubuntu_version}-{arch}`.
Finally, a third-diff enabled building with tag `{branch}-{arch}` when we build for `focal`
Test plan:
On run https://github.com/chantra/kernel-patches-runner/actions/runs/10475808508/job/29013305202
For `noble`, only the  `{branch}-{ubuntu_version}-{arch}` tag is available.
For `focal`, both are available:

Add support for Ubuntu 24.04

---

s390x.Dockerfile

This reverts commit b2a8dc58053b2fc9f47f73336c2a9f13db3d6adb.
s390x runners v2.321.0 crash with segfault on entrypoint.
Reverting to unblock the runners...

Revert "[automated] Bumping s390x containers to action-runners v2.321.0"

---

s390x.Dockerfile

Github Actions Runner.Listener x86_64 binary version 2.321.0 has been crashing with segfault on startup when emulated on s390x [1].
Ilya pointed out, that the root cause of this crash is most likely a qemu issue [2].
.NET 8 turns on "write xor execute" feature [3] by default. And GH actions runner 2.320.0->2.321.0 update includes an upgrade to .NET 8 [4].
Ilya suggested opting out of this feature in our environment to mitigate the failure.
I tested this with manually built runner immage on one for s390x BPF CI hosts: the runner doesn't crash.
[1] https://github.com/actions/runner/issues/3583
[2] https://gitlab.com/qemu-project/qemu/-/issues/2600 [3]
https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-7/#runtime:-w^x-(write-xor-execute)-support-for-all-platforms-and-architectures …

s390x: set DOTNET_EnableWriteXorExecute=0

---

.github/workflows/publish.yml

We moved all runners to noble and there is no going back. This change remove focal from the list of built containers and also generate the old tag names for noble (instead of focal).

runners: retire focal image

---

.github/workflows/publish.yml
s390x-native.Dockerfile

Add a s390x Dockerfile utilizing custom-built s390x-native runner: https://github.com/theihor/s390x-actions-runner/releases/tag/v2.321.0

Use s390x native actions runner binaries

---

.github/workflows/publish.yml
.github/workflows/version_bump.yml
Dockerfile
s390x-native.Dockerfile

Review and clean up the list of packages installed during runner image build: remove duplicates, use common list between main and s390x Dockerfiles.
* remove linux-image-generic
* replace python3 with python3-minimal.
* install LLVM with an official automatic script.
* set UBUNTU_VERSION to noble by default
This addresses recent build failures:
* https://github.com/kernel-patches/runner/actions/runs/13058686735
* https://github.com/kernel-patches/runner/actions/runs/13037837932

Fix image build

---

s390x.Dockerfile

s390x runners fail to start with:
```
exec /entrypoint.sh: exec format error
```
Needs investigation.

Revert "[automated] s390x: bump RUNNER_VERSION to v2.323.0"

---

Dockerfile
s390x.Dockerfile
token.sh

Add a check for an empty response when requesting an access token on runner startup. If no token was recieved, exit with status 199, which then can be picked up by systemd instructing it to not restart the runner container.
BPF CI runners went down recently due to the following problem:
* For some runners, after successful authentication, on attempt to recieve a job the runner app gets "Runner not found" error, which appears to be an error returned from github broker service [1].
* The systemd service maintaining the runner container automatically restarts it, leading to a frequent error -> restart loop.
* Each time container starts, the token.sh script [2] requests a runner-specific github access token. However there is a 5k/hour limit for such requests [3].
* Because there are dozens of …

Exit with special status code in token.sh on error

---

.github/workflows/publish.yml
0001-Fix-TestRunnerJobRequestMessageFromRunService_AuthMi.patch
s390x.Dockerfile

Update s390x dockerfile to use [newer gaplib](https://github.com/ppc64le/gaplib) and add a custom runner patch to mitigate a test failure.
See commits for details.

s390x v2.324.0

---

Dockerfile
README.md
install-dependencies.sh
s390x.Dockerfile

BPF CI uses various actions from libbpf/ci repo. Many of them have
system package dependencies and usually action code installs what it
needs itself.
Our self-hosted runners are docker containers. We can take advantage
of the fact that we control the docker image and pre-install common
dependencies in the image, effectively caching them.
So far this was done by hardcoding a list of some packages in
dockerfiles. A better approach is to install exactly the same packages
as libbpf/ci actions.
The first attempt to do this [1] failed, because it turned out some
dependencies (such as iproute2 needed for some BPF selftest) were only
installed in the dockerfile, and not by a relevant action.
Additionally s390x image broke because of missing dumb-init for a
similar reason.
Now that libbpf/ci part …

Cache libbpf/ci dependencies
